kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: jasonraimondi/jasonraimondi.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - latest
    - 3.1.0
