kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    repo: jasonraimondi/jasonraimondi.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
     - latest
     - ${DRONE_TAG}
    auto_tag: true
    force_tag: true

- name: notify
  image: hello-world
  when:
    status: [ success ]
    event:
    - tag
