kind: pipeline
name: default

steps:
- name: publish-latest
  image: plugins/docker
  when:
    event: push
    branch: master
  settings:
    repo: containers.jasonraimondi.com/jason/jasonraimondi.com
    registry: containers.jasonraimondi.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags = [ [ "latest" ]
    force_tag: true

- name: notify
  image: jasonraimondi/curl
  when:
    status: [ success ]
    event: push
    branch: master
  commands:
    - curl -X POST https://jasonraimondi.com/.ci/update-jason

- name: publish-tag
  image: plugins/docker
  when:
    event:
      - tag
  settings:
    repo: containers.jasonraimondi.com/jason/jasonraimondi.com
    registry: containers.jasonraimondi.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags = [
      - ${DRONE_TAG}
    auto_tag: true
    force_tag: true
