kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    when:
      event: tag
    repo: jasonraimondi/jasonraimondi.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: [ latest ]
