kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    repo: containers.jasonraimondi.com/jason/jasonraimondi.com
    registry: containers.jasonraimondi.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
     - latest
     - ${DRONE_TAG}
    auto_tag: true
    force_tag: true
