baseurl = "/"
title = "Jason Raimondi | Software Engineer"
theme ="jasontheme"
languageCode = "en-us"
enableEmoji = true
copyright = "© 2019 Jason Raimondi"
description = "Jason Raimondi is a Software Engineer based out of California."

pygmentsCodeFences=true
pygmentsUseClasses=true

defaultContentLanguage = "en"

[params]
  titleEmoji = ":tada:"
  twitter = "jsonmamondi"
  email = "jason@raimondi.us"
  profileURL = "/assets/misc/me/avatar.png"
  resumeURL = "/assets/resume/JasonRaimondi-Resume-3.2.6.pdf"

#[Permalinks]
#  post = "posts/:slug"

#[[params.menu]]
#  name = "posts"
#  url = "posts/"
#
#[[params.menu]]
#  name = "tags"
#  url = "tags/"
#
#[privacy]
#  [privacy.googleAnalytics]
#    anonymizeIP = true
#    respectDoNotTrack = true
#    useSessionStorage = true
#  [privacy.twitter]
#    enableDNT = true
#  [privacy.youtube]
#    privacyEnhanced = true
#

[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5