baseurl: ""

title: Jason Raimondi | Software Engineer
email: jason@raimondi.us
short_description: Jason Raimondi is a Software Engineer based out of Los Angeles, California.
description: >-
  Jason Raimondi is a Software Engineer focusing on web technologies based out of Los Angeles, CA.
url: "https://jasonraimondi.com"

google_analytics: "UA-54092750-4"

profile_url: "https://res.cloudinary.com/jmondi/image/upload/c_scale,w_150/v1534476066/jasonraimondi.com/me/avatar.png"

twitter_username: jsonmamondi
github_username:  jasonraimondi

timezone: America/Los_Angeles
permalink: /posts/:title
plugins:
- jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
# Add additional excludes here
- .gitignore
