baseurl: ""

title: Jason Raimondi | Software Engineer
email: jason@raimondi.us
short_description: Jason Raimondi is a Software Engineer based out of California.
description: >-
  My name is Jason Raimondi and I am a Full Stack Software Engineer from the east coast, living on the west coast. My professional focus has been in web systems; everything from designing to building and deploying server and client web applications. What I really am is a technologist and all around computer geek. Give me a computer and I will be hacking in minutes, occupied for days.
url: "https://jasonraimondi.com"

profile_url: "/assets/misc/me/avatar.png"
resume_url: "/assets/resume/JasonRaimondi-Resume-3.2.5.pdf"

twitter_username: jsonmamondi
github_username:  jasonraimondi

timezone: America/Los_Angeles
permalink: /posts/:title
plugins:
- jekyll-feed
- jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
# Add additional excludes here
- .gitignore
