name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag jasonraimondi/jasonraimondi.com:latest
        docker push jasonraimondi/jasonraimondi.com:latest
